project:
  type: website
  title: "Darius A. Görgen"
  output-dir: _site
  resources:
    - 	contents/files/cv-darius-goergen.pdf
  render:
    - "*.qmd"
    - "!py-env"
    
execute:
  freeze: auto

website:
  title: "Darius A. Görgen"
  site-url: https://www.dariusgoergen.com
  repo-url: https://github.com/goergen95/dariusgoergen
  repo-branch: gh-pages
  issue-url: https://github.com/goergen95/dariusgoergen/issues
  description: Geoinformation and Environmental Sciences
  favicon: contents/img/dg.png
  image: contents/img/dg.png
  comments:
    utterances:
      repo: goergen95/dariusgoergen
  navbar:
    collapse: true
    left:
      - href: index.html
        text: "Home"
      - href: contents/code.html
        text: "Code"
      - href: contents/blog.html
        text: "Blog"
      - href: contents/projects.html
        text: "Projects"
      - href: contents/presentations.html
        text: "Presentations"
    right:
      - href: https://github.com/goergen95/dariusgoergen
        icon: github
        aria-label: "Source Code"
  page-footer:
    left: |
      © Copyright 2023 Darius A. Görgen
      [Browse source code](https://github.com/goergen95/dariusgoergen)
    right: |
      [Impressum](https://www.dariusgoergen.com/impressum.html)
      
format:
  html:
    theme:
      light: [cosmo, theme-light.scss]
      dark:  [cosmo, theme-dark.scss]


