project:
  type: website
  resources:
    - 	contents/files/cv-darius-goergen.pdf

website:
  title: "Darius A. Görgen"
  site-url: https://dariusgoergen.com
  description: Geoinformation and Environmental Sciences
  comments:
    utterances:
      repo: goergen95/dariusgoergen
  navbar:
    right:
      - href: index.html
        text: Home
      - href: contents/blog.html
        text: "Blog"
      - href: contents/projects.html
        text: "Projects"
  page-footer:
    left: "© Copyright 2022 Darius A. Görgen."

format:
  html:
    theme:
      light: [cosmo, theme-light.scss]
      dark:  [cosmo, theme-dark.scss]


