project:
  type: site
  title: "Darius A. Görgen"
  output-dir: _site
  resources:
    - 	contents/files/cv-darius-goergen.pdf
  render:
    - "*.qmd"
    - "!py-env"
  favicon: contents/img/dg.png
    
execute:
  freeze: auto

site:
  title: "Darius A. Görgen"
  site-url: https://dariusgoergen.com
  site-path: '/'
  description: Geoinformation and Environmental Sciences
  twitter-card:
    creator: "@darius_goergen"
  comments:
    utterances:
      repo: goergen95/dariusgoergen
  navbar:
    left:
      - href: index.html
        text: "Home"
      - href: contents/blog.html
        text: "Blog"
      - href: contents/projects.html
        text: "Projects"
    right:
      - href: https://github.com/goergen95/dariusgoergen
        icon: github
        aria-label: "Source Code"
  page-footer:
    left: |
      © Copyright 2022 Darius A. Görgen
      [Browse source code](https://github.com/goergen95/dariusgoergen)
    right: |
      [Impressum](https://www.dariusgoergen.com/impressum.html)

format:
  html:
    theme:
      light: [cosmo, theme-light.scss]
      dark:  [cosmo, theme-dark.scss]


